language: node_js

cache: 
  directories:
    - ~/.npm
notifications:
  email:
    recipients: 
      - hanna.w28@gmail.com
    on_success: always
    on_failure: always 
node_js: 
  - '9'
git: 
  depth: 3
script:
  - yarn build
deploy: 
  provider: pages
  skip-cleanup: true
  keep-history: true
  target-branch: master
  on:
    branch: develop